# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
      fetchSubmodules = false;
      sha256 = "sha256-8zVOkoMXkKQ+SCBg7jYn2H+RP7bb9x8MAOy/8d/P6Cc=";
    };
    date = "2025-11-07";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "6f88dff82b786e879b255a8e1523547c4f62d031";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "6f88dff82b786e879b255a8e1523547c4f62d031";
      fetchSubmodules = false;
      sha256 = "sha256-0BRHE7O3rcgLa6wg8GVPu9R0MDsA87D6jGbA7bHZ7N0=";
    };
    date = "2025-05-18";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-main = {
    pname = "kernelsu-main";
    version = "4217515035b3122f296d064c43beb3b83e2bb330";
    src = fetchgit {
      url = "https://github.com/tiann/KernelSU.git";
      rev = "4217515035b3122f296d064c43beb3b83e2bb330";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0SngV34ZOgWUWFUD/pLrFqVU4ksztWQbT8OwNuHGPpc=";
    };
    date = "2025-12-26";
  };
  kernelsu-main-revision-code = {
    pname = "kernelsu-main-revision-code";
    version = "32179";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-b1Y1A182rVALT8S7eBa7cu9VlOG8rkT6B0xemI/EwP4=";
    };
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "v3.0.0";
    src = fetchgit {
      url = "https://github.com/KernelSU-Next/KernelSU-Next.git";
      rev = "v3.0.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VmmDo7d54TcVAMeFIctz+F/dSQb2YmSAbiYo5vT4vrw=";
    };
  };
  kernelsu-next-revision-code = {
    pname = "kernelsu-next-revision-code";
    version = "32857";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-b1Y1A182rVALT8S7eBa7cu9VlOG8rkT6B0xemI/EwP4=";
    };
  };
  oneplus-ace3-lineageos-22_1 = {
    pname = "oneplus-ace3-lineageos-22_1";
    version = "e4621a167b4cd806178eb76f1c481d8ee07a0e7a";
    src = fetchFromGitHub {
      owner = "OnePlus12R-development";
      repo = "android_kernel_oneplus_sm8550";
      rev = "e4621a167b4cd806178eb76f1c481d8ee07a0e7a";
      fetchSubmodules = false;
      sha256 = "sha256-grgtJulkBH3IgNlaQX/u91Vq8j2wMTv6rEt3dWwm5gE=";
    };
    date = "2025-02-23";
  };
  susfs-android14-5_15 = {
    pname = "susfs-android14-5_15";
    version = "2932a2deb506fdd39621ab43b7daa16c2798a12b";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "2932a2deb506fdd39621ab43b7daa16c2798a12b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Nlm8+w+xbOGl2FL0R0FhgdY0KI4Etsx91Aooj2yMjes=";
    };
    date = "2025-12-21";
  };
  wildplus-kernel-patches = {
    pname = "wildplus-kernel-patches";
    version = "f8a54b93d9f8515f1df00ef189ef49bdff32eed8";
    src = fetchFromGitHub {
      owner = "WildPlusKernel";
      repo = "kernel_patches";
      rev = "f8a54b93d9f8515f1df00ef189ef49bdff32eed8";
      fetchSubmodules = false;
      sha256 = "sha256-b/V73Itf6xnakvMP8EKASc9+xkSJJqJweSf6w1T80Es=";
    };
    date = "2025-12-24";
  };
}
