# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
      fetchSubmodules = false;
      sha256 = "sha256-8zVOkoMXkKQ+SCBg7jYn2H+RP7bb9x8MAOy/8d/P6Cc=";
    };
    date = "2025-11-07";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "1c9a500dd4aa8081952523126e97eb155aed941b";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "1c9a500dd4aa8081952523126e97eb155aed941b";
      fetchSubmodules = false;
      sha256 = "sha256-lADQ+Fyo5kX+At2O5xnBOs8R9XIctQS2GlLlT/bfWew=";
    };
    date = "2026-07-04";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-main = {
    pname = "kernelsu-main";
    version = "63b175d8c37482c9fd25fb9bc341289667e4ce57";
    src = fetchgit {
      url = "https://github.com/tiann/KernelSU.git";
      rev = "63b175d8c37482c9fd25fb9bc341289667e4ce57";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-d5u6nuDOt4ZiLmm42jMUcxK443HXUL4M1VkRF3VvjDA=";
    };
    date = "2026-07-30";
  };
  kernelsu-main-revision-code = {
    pname = "kernelsu-main-revision-code";
    version = "32525";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-/2ep12TWojZ6GHc05pf2pTIX25ohwQHUEKETyocaKZ0=";
    };
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "v3.3.0";
    src = fetchgit {
      url = "https://github.com/KernelSU-Next/KernelSU-Next.git";
      rev = "v3.3.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/7IuX9dIH39CZ6t0jJRTwEQs95U0Vx9xsxdiiDYi5jM=";
    };
  };
  kernelsu-next-revision-code = {
    pname = "kernelsu-next-revision-code";
    version = "33214";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-/2ep12TWojZ6GHc05pf2pTIX25ohwQHUEKETyocaKZ0=";
    };
  };
  oneplus-ace3-lineageos-22_1 = {
    pname = "oneplus-ace3-lineageos-22_1";
    version = "e4621a167b4cd806178eb76f1c481d8ee07a0e7a";
    src = fetchFromGitHub {
      owner = "OnePlus12R-development";
      repo = "android_kernel_oneplus_sm8550";
      rev = "e4621a167b4cd806178eb76f1c481d8ee07a0e7a";
      fetchSubmodules = false;
      sha256 = "sha256-grgtJulkBH3IgNlaQX/u91Vq8j2wMTv6rEt3dWwm5gE=";
    };
    date = "2025-02-23";
  };
  susfs-android14-5_15 = {
    pname = "susfs-android14-5_15";
    version = "0463ac089308014e8c22cc6a4558e0d6d2a53e08";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "0463ac089308014e8c22cc6a4558e0d6d2a53e08";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SRiJxFtv8+b2Qu/rtFp+1X/2u5s5Tqm43/p/m06sNB4=";
    };
    date = "2026-07-31";
  };
  wildplus-kernel-patches = {
    pname = "wildplus-kernel-patches";
    version = "ef2fff764581f30d066ad77bf9a311cbbec82da9";
    src = fetchFromGitHub {
      owner = "WildPlusKernel";
      repo = "kernel_patches";
      rev = "ef2fff764581f30d066ad77bf9a311cbbec82da9";
      fetchSubmodules = false;
      sha256 = "sha256-Yp63vNqzkcSeO5/k/bg1OE2i7GIO4hC6KoAafmVa7FE=";
    };
    date = "2026-07-31";
  };
}
